apiVersion: v1
kind: Service
metadata:
   name: proxy
   namespace: {{ namespace }}
   labels:
      app: proxy-svc
spec:
   ports:
   -  port: {{ APPS.PROXY.CONTAINERPORT }}
      protocol: TCP
   selector:
      app: proxy-ms
   externalIPs:
   -  {{ ansible_default_ipv4.address }} 

