apiVersion: v1
kind: Secret
metadata:
  name: mongodb
  namespace: {{ namespace }}
type: Opaque
data:
  database-password: {{ common.password }}
  database-user: {{ common.username }}
  database-name: {{ common.servicename }}

