---
apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: mongo
  labels:
    app: mongodb
spec:
  ports:
  - port: 27027
    targetPort: 27017
    protocol: TCP
    name: dbport
  selector:
    app: mongodb
  clusterIP: None

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: mongo
  labels:
    app: mongodb
spec:
  replicas: 5
  serviceName: db
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:latest
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - mountPath: "/data"
          name: mongodbdata
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_DATABASE
          valueFrom:
            configMapKeyRef:
              name: mongodb
              key: database-name
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb
              key: database-user
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb
              key: database-password
  volumeClaimTemplates:
  - metadata:
      name: mongodbdata
    spec:
      storageClassName: manual
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 100Mi


